version: '3'
services:
  frontend:
    container_name: myproject1_frontend
    build: frontend/
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./frontend/src/
        target: /project/app/myapp/src/
